### ISSUE TITLE
Exception in thread "main" java.util.NoSuchElementException

### ISSUE THREAD

**Issue by mdjong4** [sumoDave/GarminDiveFitAppender#1]
I'm trying to combine FIT files, but keep getting the following error;
Processing file: C:\\Temp\\1.fit
Processing file: C:\\Temp\\2.fit
Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.ArrayList.getLast(ArrayList.java:454)
        at DiveProfile.reuseTimeInZonesMessage(DiveProfile.java:335)
        at Main.getNewDiveProfileMessageList(Main.java:160)
        at Main.main(Main.java:32)

Is it possible to upload the source code, so I can trace what's going wrong?
FIT files were created with a Garmin Descent MK2.
Code running with JDK 21.0.1.

**Comment by sumoDave** [comment]
Exception was thrown because I was attempting to reuse TimeInZonesMessage from original files. These message do not exist in your original fit files, so it's throwing an exception. 

Added conditional checks for optional messages prior to re-usage.
