### ISSUE TITLE
unable to merge files 

### ISSUE THREAD

**Issue by UrbaneMyth** [sumoDave/GarminDiveFitAppender#10]
Hi I've tried using your merge files app but get the following error 

Processing file: C:\Users\johnsavage\Documents\8816553793_ACTIVITY.fit
Processing file: C:\Users\johnsavage\Documents\8744127956_ACTIVITY.fit
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.garmin.fit.SessionMesg.getTotalDescent()" is null
        at GenericProfile.setAggregateValues(GenericProfile.java:194)
        at GenericProfile.initialiseData(GenericProfile.java:59)
        at DiveProfile.initialiseData(DiveProfile.java:8)
        at Main.main(Main.java:76)

**Comment by sumoDave** [comment]
Can you please attach the fit files so I can investigate?

**Comment by adlaigoldberg** [comment]
Hi Dave.   Thanks for pulling this together.  Looking forward to making this so much easier than manual adjustments.

Have been trying to unzip GarminDiveFitAppender.zip on my Mac.  Says the Mac Archive Utility doesn't support this format.  Which file compressor did you use?

Adlai

**Comment by sumoDave** [comment]
> Hi Dave. Thanks for pulling this together. Looking forward to making this so much easier than manual adjustments.
> 
> Have been trying to unzip GarminDiveFitAppender.zip on my Mac. Says the Mac Archive Utility doesn't support this format. Which file compressor did you use?
> 
> Adlai

My IDE automagically generates it for me. Have you tried unzipping via the command line? or use a utility such as p7zip?

**Comment by sumoDave** [comment]
Fixed in release v3.4.0
