### ISSUE TITLE
Null issue

### ISSUE THREAD

**Issue by nbaldus** [sumoDave/GarminDiveFitAppender#11]
Hello and welcome!

Processing file: C:\Users\nicho\OneDrive\Desktop\New folder\10406392179_ACTIVITY.fit
Processing file: C:\Users\nicho\OneDrive\Desktop\New folder\10406404948_ACTIVITY.fit
Processing file: C:\Users\nicho\OneDrive\Desktop\New folder\10406405984_ACTIVITY.fit
Processing file: C:\Users\nicho\OneDrive\Desktop\New folder\10406407224_ACTIVITY.fit
Processing file: C:\Users\nicho\OneDrive\Desktop\New folder\10406407743_ACTIVITY.fit
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "next" is null
        at java.base/java.util.Collections.max(Collections.java:702)
        at GenericProfile.setAggregateValues(GenericProfile.java:209)
        at GenericProfile.initialiseData(GenericProfile.java:59)
        at DiveProfile.initialiseData(DiveProfile.java:8)
        at Main.main(Main.java:76)
Press any key to continue . . .

[10406392179.zip](https://github.com/user-attachments/files/17534569/10406392179.zip)
[10406404948.zip](https://github.com/user-attachments/files/17534570/10406404948.zip)
[10406405984.zip](https://github.com/user-attachments/files/17534571/10406405984.zip)
[10406407224.zip](https://github.com/user-attachments/files/17534572/10406407224.zip)
[10406407743.zip](https://github.com/user-attachments/files/17534573/10406407743.zip)

**Comment by sumoDave** [comment]
Descent Mk1 fit files don't seem to include "training load peak" data in the session messages.

**Comment by sumoDave** [comment]
Resolved with release v.3.2.0
