### ISSUE TITLE
Java Issue?

### ISSUE THREAD

**Issue by nicyjones** [sumoDave/GarminDiveFitAppender#6]
When I attempt to drag and drop the ".fit" files onto the batch file, I receive the following error.

Exception in thread "main" java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Press any key to continue . . .

I am curious if you had any input as I believe your application is EXACTLY what I am needing.

I did not initially have JRE installed so I installed the latest version. 

Environment: 
Edition	Windows 11 Home
Version	23H2
Installed on	‎2/‎11/‎2023
OS build	22631.3880
Serial number	PF33BF1H
Experience	Windows Feature Experience Pack 1000.22700.1020.0

Device:
Device name	DESKTOP-T21QL5O
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	12.0 GB (11.8 GB usable)
Device ID	AE1EAADF-E88F-4AE6-A75F-9F70F7CE5A67
Product ID	00342-21923-68480-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

JRE Version 1.8.0_421

Thank you for your help!

**Comment by sumoDave** [comment]
Although update 421 was just released, it is still only for Java 8. My utility requires minimum Java 21. 

You will need to install the latest JDK. From around Java 11, they (Oracle) stopped making a publicly available JRE. 
Recommended builds (any one of these will do - sourced from https://whichjdk.com/):
[Azul Zulu](https://www.azul.com/downloads/?package=jdk#download-openjdk)
[Adoptium Eclipse Temurin](https://adoptium.net/temurin/releases/)

You can also download from oracle, although these are only updated for 6months post release:
[Oracle OpenJDK](https://jdk.java.net/)
